export const fallbackCityPrices = {
  2746: {
    city_id: 2746,
    city_name: "Pensacola",
    state_code: "FL",
    country_name: "United States",
    exchange_rate: {
      EUR: 0.8530996522765817,
      AUD: 1.5460733529205013,
      USD: 1,
      CAD: 1.3874505628751503,
      CNY: 7.167751809424363,
      CZK: 20.92320311620241,
      DKK: 6.369037259980413,
      GBP: 0.7452951554176945,
      HKD: 7.8144576504270615,
      JPY: 147.6050438663841,
      NZD: 1.7046091268013197,
      NOK: 10.056600602629594,
      RUB: 79.83285389132875,
      KRW: 1384.2007249640844,
      CHF: 0.8081242386085603,
      UAH: 40.87732085760402,
      SEK: 9.493348382011199,
    },
    exchange_rates_updated: {
      date: "2025-08-24",
      timestamp: 1756058657,
    },
    prices: [
      {
        good_id: 1,
        item_name:
          "Price per square meter to Buy Apartment Outside of City Center",
        category_id: 1,
        category_name: "Buy Apartment",
        min: 906.56,
        avg: 979.96,
        max: 1065.63,
        usd: {
          min: "906.56",
          avg: "979.96",
          max: "1065.63",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 2,
        item_name: "Price per square meter to Buy Apartment in City Center",
        category_id: 1,
        category_name: "Buy Apartment",
        min: 1510.53,
        avg: 2166.62,
        max: 2822.71,
        usd: {
          min: "1510.53",
          avg: "2166.62",
          max: "2822.71",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 3,
        item_name: "International Primary School, Yearly for 1 Child",
        category_id: 2,
        category_name: "Childcare",
        min: 9000,
        avg: 10000,
        max: 11000,
        usd: {
          min: "9000.00",
          avg: "10000.00",
          max: "11000.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 4,
        item_name: "Private Preschool or Kindergarten, Monthly for 1 Child",
        category_id: 2,
        category_name: "Childcare",
        min: 360,
        avg: 733.33,
        max: 1200,
        usd: {
          min: "360.00",
          avg: "733.33",
          max: "1200.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 5,
        item_name:
          "Pair of Jeans in a Chain Store Like George, H&M, Zara, etc.",
        category_id: 3,
        category_name: "Clothing And Shoes",
        min: 29.99,
        avg: 48.75,
        max: 69,
        usd: {
          min: "29.99",
          avg: "48.75",
          max: "69.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 6,
        item_name: "Pair of Leather Business Shoes",
        category_id: 3,
        category_name: "Clothing And Shoes",
        min: 50,
        avg: 100,
        max: 150,
        usd: {
          min: "50.00",
          avg: "100.00",
          max: "150.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 7,
        item_name: "Pair of Running Shoes, Mid-Range Price",
        category_id: 3,
        category_name: "Clothing And Shoes",
        min: 53,
        avg: 83.57,
        max: 114.14,
        usd: {
          min: "53.00",
          avg: "83.57",
          max: "114.14",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 9,
        item_name: "Apples, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 2.2,
        avg: 5.32,
        max: 11.02,
        usd: {
          min: "2.20",
          avg: "5.32",
          max: "11.02",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 10,
        item_name: "Banana, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 1.1,
        avg: 2.12,
        max: 3.97,
        usd: {
          min: "1.10",
          avg: "2.12",
          max: "3.97",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 11,
        item_name: "Beef Round or Equivalent Back Leg Red Meat, 1 kg ",
        category_id: 4,
        category_name: "Markets",
        min: 11,
        avg: 17.51,
        max: 24.02,
        usd: {
          min: "11.00",
          avg: "17.51",
          max: "24.02",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 12,
        item_name: "Bottle of Wine, Mid-Range Price",
        category_id: 4,
        category_name: "Markets",
        min: 5,
        avg: 7,
        max: 10,
        usd: {
          min: "5.00",
          avg: "7.00",
          max: "10.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 13,
        item_name: "Chicken Breasts, Boneless and Skinless, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 4.12,
        avg: 7.22,
        max: 15.41,
        usd: {
          min: "4.12",
          avg: "7.22",
          max: "15.41",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 14,
        item_name: "Domestic Beer, 0.5 liter Bottle",
        category_id: 4,
        category_name: "Markets",
        min: 0.94,
        avg: 1.81,
        max: 3,
        usd: {
          min: "0.94",
          avg: "1.81",
          max: "3.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 15,
        item_name: "Eggs, 12 pack",
        category_id: 4,
        category_name: "Markets",
        min: 1.2,
        avg: 2.24,
        max: 3.28,
        usd: {
          min: "1.20",
          avg: "2.24",
          max: "3.28",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 17,
        item_name: "Lettuce, 1 head",
        category_id: 4,
        category_name: "Markets",
        min: 1.28,
        avg: 1.59,
        max: 2,
        usd: {
          min: "1.28",
          avg: "1.59",
          max: "2.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 18,
        item_name: "Loaf of Fresh White Bread, 0.5 kg",
        category_id: 4,
        category_name: "Markets",
        min: 1.65,
        avg: 2.97,
        max: 4.29,
        usd: {
          min: "1.65",
          avg: "2.97",
          max: "4.29",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 19,
        item_name: "Local Cheese, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 6.61,
        avg: 7.1,
        max: 8.07,
        usd: {
          min: "6.61",
          avg: "7.10",
          max: "8.07",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 20,
        item_name: "Milk, Regular,1 liter",
        category_id: 4,
        category_name: "Markets",
        min: 0.88,
        avg: 1.1,
        max: 1.32,
        usd: {
          min: "0.88",
          avg: "1.10",
          max: "1.32",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 21,
        item_name: "Onion, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 1.94,
        avg: 2.62,
        max: 3.73,
        usd: {
          min: "1.94",
          avg: "2.62",
          max: "3.73",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 22,
        item_name: "Oranges, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 2.2,
        avg: 2.23,
        max: 2.27,
        usd: {
          min: "2.20",
          avg: "2.23",
          max: "2.27",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 23,
        item_name: "Pack of Cigarettes",
        category_id: 4,
        category_name: "Markets",
        min: 6.5,
        avg: 7,
        max: 13,
        usd: {
          min: "6.50",
          avg: "7.00",
          max: "13.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 24,
        item_name: "Potato, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 1.3,
        avg: 2.53,
        max: 3.76,
        usd: {
          min: "1.30",
          avg: "2.53",
          max: "3.76",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 25,
        item_name: "White Rice, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 1.59,
        avg: 2.94,
        max: 4.41,
        usd: {
          min: "1.59",
          avg: "2.94",
          max: "4.41",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 26,
        item_name: "Tomato, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 1.1,
        avg: 3.77,
        max: 6.44,
        usd: {
          min: "1.10",
          avg: "3.77",
          max: "6.44",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 27,
        item_name: "Water, 1.5 liter Bottle",
        category_id: 4,
        category_name: "Markets",
        min: 1.2,
        avg: 1.76,
        max: 2.32,
        usd: {
          min: "1.20",
          avg: "1.76",
          max: "2.32",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 28,
        item_name: "One bedroom apartment outside of city centre",
        category_id: 5,
        category_name: "Rent Per Month",
        min: 650,
        avg: 838,
        max: 1200,
        usd: {
          min: "650.00",
          avg: "838.00",
          max: "1200.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 29,
        item_name: "One bedroom apartment in city centre",
        category_id: 5,
        category_name: "Rent Per Month",
        min: 850,
        avg: 988.89,
        max: 1200,
        usd: {
          min: "850.00",
          avg: "988.89",
          max: "1200.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 30,
        item_name: "Three bedroom apartment outside of city centre",
        category_id: 5,
        category_name: "Rent Per Month",
        min: 1000,
        avg: 1293.89,
        max: 1800,
        usd: {
          min: "1000.00",
          avg: "1293.89",
          max: "1800.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 31,
        item_name: "Three bedroom apartment in city centre",
        category_id: 5,
        category_name: "Rent Per Month",
        min: 1200,
        avg: 1566.11,
        max: 2500,
        usd: {
          min: "1200.00",
          avg: "1566.11",
          max: "2500.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 32,
        item_name: "Cappuccino",
        category_id: 6,
        category_name: "Restaurants",
        min: 3,
        avg: 3.83,
        max: 5,
        usd: {
          min: "3.00",
          avg: "3.83",
          max: "5.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 33,
        item_name: "Coca-Cola, 0.33 liter Bottle",
        category_id: 6,
        category_name: "Restaurants",
        min: 1.75,
        avg: 1.88,
        max: 2.01,
        usd: {
          min: "1.75",
          avg: "1.88",
          max: "2.01",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 34,
        item_name: "Domestic Beer, 0.5 liter Draught",
        category_id: 6,
        category_name: "Restaurants",
        min: 3.6,
        avg: 4,
        max: 4.4,
        usd: {
          min: "3.60",
          avg: "4.00",
          max: "4.40",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 35,
        item_name: "Imported Beer, 0.33 liter Bottle",
        category_id: 6,
        category_name: "Restaurants",
        min: 4.5,
        avg: 5,
        max: 5.5,
        usd: {
          min: "4.50",
          avg: "5.00",
          max: "5.50",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 36,
        item_name: "McMeal at McDonalds or Alternative Combo Meal",
        category_id: 6,
        category_name: "Restaurants",
        min: 6,
        avg: 7,
        max: 8,
        usd: {
          min: "6.00",
          avg: "7.00",
          max: "8.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 37,
        item_name: "Meal for 2 People, Mid-range Restaurant, Three-course",
        category_id: 6,
        category_name: "Restaurants",
        min: 45,
        avg: 50,
        max: 55,
        usd: {
          min: "45.00",
          avg: "50.00",
          max: "55.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 38,
        item_name: "Meal in Inexpensive Restaurant",
        category_id: 6,
        category_name: "Restaurants",
        min: 9,
        avg: 10,
        max: 11,
        usd: {
          min: "9.00",
          avg: "10.00",
          max: "11.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 40,
        item_name: "Average Monthly Net Salary, After Tax",
        category_id: 7,
        category_name: "Salaries And Financing",
        min: 1856.7,
        avg: 2063,
        max: 2269.3,
        usd: {
          min: "1856.70",
          avg: "2063.00",
          max: "2269.30",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 42,
        item_name: "Cinema ticket, 1 Seat",
        category_id: 8,
        category_name: "Sports And Leisure",
        min: 8,
        avg: 10,
        max: 12,
        usd: {
          min: "8.00",
          avg: "10.00",
          max: "12.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 43,
        item_name: "Fitness Club, Monthly Fee for 1 Adult",
        category_id: 8,
        category_name: "Sports And Leisure",
        min: 19,
        avg: 28.57,
        max: 45,
        usd: {
          min: "19.00",
          avg: "28.57",
          max: "45.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 44,
        item_name: "Tennis Court Rent, 1 Hour on Weekend",
        category_id: 8,
        category_name: "Sports And Leisure",
        min: 11.25,
        avg: 12.5,
        max: 13.75,
        usd: {
          min: "11.25",
          avg: "12.50",
          max: "13.75",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 45,
        item_name: "Gasoline, 1 liter",
        category_id: 9,
        category_name: "Transportation",
        min: 0.5,
        avg: 0.6,
        max: 0.7,
        usd: {
          min: "0.50",
          avg: "0.60",
          max: "0.70",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 46,
        item_name: "Monthly Pass, Regular Price",
        category_id: 9,
        category_name: "Transportation",
        min: 35,
        avg: 45,
        max: 100,
        usd: {
          min: "35.00",
          avg: "45.00",
          max: "100.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 47,
        item_name: "One-way Ticket, Local Transport",
        category_id: 9,
        category_name: "Transportation",
        min: 1,
        avg: 1.5,
        max: 2,
        usd: {
          min: "1.00",
          avg: "1.50",
          max: "2.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 48,
        item_name: "Taxi, price for 1 hour Waiting, Normal Tariff",
        category_id: 9,
        category_name: "Transportation",
        min: 20,
        avg: 26,
        max: 32,
        usd: {
          min: "20.00",
          avg: "26.00",
          max: "32.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 49,
        item_name: "Taxi, price for 1 km, Normal Tariff",
        category_id: 9,
        category_name: "Transportation",
        min: 1.24,
        avg: 1.4,
        max: 2.49,
        usd: {
          min: "1.24",
          avg: "1.40",
          max: "2.49",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 50,
        item_name: "Taxi Start, Normal Tariff",
        category_id: 9,
        category_name: "Transportation",
        min: 1.8,
        avg: 2,
        max: 2.2,
        usd: {
          min: "1.80",
          avg: "2.00",
          max: "2.20",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 52,
        item_name:
          "Volkswagen Golf 1.4 90 KW Trendline (Or Equivalent New Car)",
        category_id: 9,
        category_name: "Transportation",
        min: 19800,
        avg: 22000,
        max: 24200,
        usd: {
          min: "19800.00",
          avg: "22000.00",
          max: "24200.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 53,
        item_name:
          "Prepaid Mobile Tariff Local, price per 1 min, No Discounts or Plans",
        category_id: 10,
        category_name: "Utilities Per Month",
        min: 0.02,
        avg: 0.02,
        max: 0.02,
        usd: {
          min: "0.02",
          avg: "0.02",
          max: "0.02",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 54,
        item_name:
          "Basic utilities for 85 square meter Apartment including Electricity, Heating or Cooling, Water and Garbage",
        category_id: 10,
        category_name: "Utilities Per Month",
        min: 135,
        avg: 264.22,
        max: 564,
        usd: {
          min: "135.00",
          avg: "264.22",
          max: "564.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 55,
        item_name: "Internet, 60 Mbps or More, Unlimited Data, Cable/ADSL",
        category_id: 10,
        category_name: "Utilities Per Month",
        min: 50,
        avg: 64.78,
        max: 150,
        usd: {
          min: "50.00",
          avg: "64.78",
          max: "150.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 58,
        item_name: "Water, 0.33 liter Bottle",
        category_id: 4,
        category_name: "Markets",
        min: 1,
        avg: 1.39,
        max: 1.78,
        usd: {
          min: "1.00",
          avg: "1.39",
          max: "1.78",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 64,
        item_name: "Summer Dress in a Chain Store Like George, H&M, Zara, etc.",
        category_id: 3,
        category_name: "Clothing And Shoes",
        min: 20,
        avg: 34.83,
        max: 50,
        usd: {
          min: "20.00",
          avg: "34.83",
          max: "50.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 65,
        item_name:
          "Mortgage Interest Rate in Percentages for 20 Years Fixed-Rate, Yearly, Fixed-Rate",
        category_id: 7,
        category_name: "Salaries And Financing",
        min: 3.67,
        avg: 4.08,
        max: 4.49,
        measure: "percent",
      },
      {
        good_id: 68,
        item_name: "Imported Beer, 0.33 liter Bottle",
        category_id: 4,
        category_name: "Markets",
        min: 1,
        avg: 3.17,
        max: 5.34,
        usd: {
          min: "1.00",
          avg: "3.17",
          max: "5.34",
        },
        measure: "money",
        currency_code: "USD",
      },
    ],
    error: null,
  },
  2701: {
    city_id: 2701,
    city_name: "New York",
    state_code: "NY",
    country_name: "United States",
    exchange_rate: {
      EUR: 0.8530996522765817,
      AUD: 1.5460733529205013,
      USD: 1,
      CAD: 1.3874505628751503,
      CNY: 7.167751809424363,
      CZK: 20.92320311620241,
      DKK: 6.369037259980413,
      GBP: 0.7452951554176945,
      HKD: 7.8144576504270615,
      JPY: 147.6050438663841,
      NZD: 1.7046091268013197,
      NOK: 10.056600602629594,
      RUB: 79.83285389132875,
      KRW: 1384.2007249640844,
      CHF: 0.8081242386085603,
      UAH: 40.87732085760402,
      SEK: 9.493348382011199,
    },
    exchange_rates_updated: {
      date: "2025-08-24",
      timestamp: 1756058657,
    },
    prices: [
      {
        good_id: 1,
        item_name:
          "Price per square meter to Buy Apartment Outside of City Center",
        category_id: 1,
        category_name: "Buy Apartment",
        min: 3767.37,
        avg: 8048.65,
        max: 12329.93,
        usd: {
          min: "3767.37",
          avg: "8048.65",
          max: "12329.93",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 2,
        item_name: "Price per square meter to Buy Apartment in City Center",
        category_id: 1,
        category_name: "Buy Apartment",
        min: 10919,
        avg: 16308.41,
        max: 21697.82,
        usd: {
          min: "10919.00",
          avg: "16308.41",
          max: "21697.82",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 3,
        item_name: "International Primary School, Yearly for 1 Child",
        category_id: 2,
        category_name: "Childcare",
        min: 30000,
        avg: 39200,
        max: 50000,
        usd: {
          min: "30000.00",
          avg: "39200.00",
          max: "50000.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 4,
        item_name: "Private Preschool or Kindergarten, Monthly for 1 Child",
        category_id: 2,
        category_name: "Childcare",
        min: 1600,
        avg: 2479.17,
        max: 3500,
        usd: {
          min: "1600.00",
          avg: "2479.17",
          max: "3500.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 5,
        item_name:
          "Pair of Jeans in a Chain Store Like George, H&M, Zara, etc.",
        category_id: 3,
        category_name: "Clothing And Shoes",
        min: 30,
        avg: 58.52,
        max: 100,
        usd: {
          min: "30.00",
          avg: "58.52",
          max: "100.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 6,
        item_name: "Pair of Leather Business Shoes",
        category_id: 3,
        category_name: "Clothing And Shoes",
        min: 70,
        avg: 142.63,
        max: 275,
        usd: {
          min: "70.00",
          avg: "142.63",
          max: "275.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 7,
        item_name: "Pair of Running Shoes, Mid-Range Price",
        category_id: 3,
        category_name: "Clothing And Shoes",
        min: 60,
        avg: 89.66,
        max: 120,
        usd: {
          min: "60.00",
          avg: "89.66",
          max: "120.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 9,
        item_name: "Apples, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 2.2,
        avg: 6.12,
        max: 10.04,
        usd: {
          min: "2.20",
          avg: "6.12",
          max: "10.04",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 10,
        item_name: "Banana, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 1.1,
        avg: 2.84,
        max: 6.61,
        usd: {
          min: "1.10",
          avg: "2.84",
          max: "6.61",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 11,
        item_name: "Beef Round or Equivalent Back Leg Red Meat, 1 kg ",
        category_id: 4,
        category_name: "Markets",
        min: 9.92,
        avg: 16.28,
        max: 33.05,
        usd: {
          min: "9.92",
          avg: "16.28",
          max: "33.05",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 12,
        item_name: "Bottle of Wine, Mid-Range Price",
        category_id: 4,
        category_name: "Markets",
        min: 8.99,
        avg: 15,
        max: 25,
        usd: {
          min: "8.99",
          avg: "15.00",
          max: "25.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 13,
        item_name: "Chicken Breasts, Boneless and Skinless, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 6.61,
        avg: 13.64,
        max: 24.25,
        usd: {
          min: "6.61",
          avg: "13.64",
          max: "24.25",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 14,
        item_name: "Domestic Beer, 0.5 liter Bottle",
        category_id: 4,
        category_name: "Markets",
        min: 1.79,
        avg: 3.06,
        max: 4.33,
        usd: {
          min: "1.79",
          avg: "3.06",
          max: "4.33",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 15,
        item_name: "Eggs, 12 pack",
        category_id: 4,
        category_name: "Markets",
        min: 1.79,
        avg: 3.35,
        max: 5.51,
        usd: {
          min: "1.79",
          avg: "3.35",
          max: "5.51",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 17,
        item_name: "Lettuce, 1 head",
        category_id: 4,
        category_name: "Markets",
        min: 1.29,
        avg: 2.2,
        max: 3.11,
        usd: {
          min: "1.29",
          avg: "2.20",
          max: "3.11",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 18,
        item_name: "Loaf of Fresh White Bread, 0.5 kg",
        category_id: 4,
        category_name: "Markets",
        min: 2.2,
        avg: 3.78,
        max: 7.15,
        usd: {
          min: "2.20",
          avg: "3.78",
          max: "7.15",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 19,
        item_name: "Local Cheese, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 8,
        avg: 15.14,
        max: 30.84,
        usd: {
          min: "8.00",
          avg: "15.14",
          max: "30.84",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 20,
        item_name: "Milk, Regular,1 liter",
        category_id: 4,
        category_name: "Markets",
        min: 0.79,
        avg: 1.2,
        max: 2.11,
        usd: {
          min: "0.79",
          avg: "1.20",
          max: "2.11",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 21,
        item_name: "Onion, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 1.74,
        avg: 3.88,
        max: 6.61,
        usd: {
          min: "1.74",
          avg: "3.88",
          max: "6.61",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 22,
        item_name: "Oranges, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 2.2,
        avg: 5.22,
        max: 11.02,
        usd: {
          min: "2.20",
          avg: "5.22",
          max: "11.02",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 23,
        item_name: "Pack of Cigarettes",
        category_id: 4,
        category_name: "Markets",
        min: 13,
        avg: 15,
        max: 20,
        usd: {
          min: "13.00",
          avg: "15.00",
          max: "20.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 24,
        item_name: "Potato, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 1.32,
        avg: 4.18,
        max: 8.82,
        usd: {
          min: "1.32",
          avg: "4.18",
          max: "8.82",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 25,
        item_name: "White Rice, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 2.2,
        avg: 5.73,
        max: 11.02,
        usd: {
          min: "2.20",
          avg: "5.73",
          max: "11.02",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 26,
        item_name: "Tomato, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 2.18,
        avg: 5.72,
        max: 11,
        usd: {
          min: "2.18",
          avg: "5.72",
          max: "11.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 27,
        item_name: "Water, 1.5 liter Bottle",
        category_id: 4,
        category_name: "Markets",
        min: 1,
        avg: 2.09,
        max: 3.18,
        usd: {
          min: "1.00",
          avg: "2.09",
          max: "3.18",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 28,
        item_name: "One bedroom apartment outside of city centre",
        category_id: 5,
        category_name: "Rent Per Month",
        min: 1600,
        avg: 2010.53,
        max: 2700,
        usd: {
          min: "1600.00",
          avg: "2010.53",
          max: "2700.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 29,
        item_name: "One bedroom apartment in city centre",
        category_id: 5,
        category_name: "Rent Per Month",
        min: 2500,
        avg: 3364.29,
        max: 4507,
        usd: {
          min: "2500.00",
          avg: "3364.29",
          max: "4507.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 30,
        item_name: "Three bedroom apartment outside of city centre",
        category_id: 5,
        category_name: "Rent Per Month",
        min: 2400,
        avg: 3482.68,
        max: 5000,
        usd: {
          min: "2400.00",
          avg: "3482.68",
          max: "5000.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 31,
        item_name: "Three bedroom apartment in city centre",
        category_id: 5,
        category_name: "Rent Per Month",
        min: 4500,
        avg: 6560.09,
        max: 10000,
        usd: {
          min: "4500.00",
          avg: "6560.09",
          max: "10000.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 32,
        item_name: "Cappuccino",
        category_id: 6,
        category_name: "Restaurants",
        min: 3.5,
        avg: 4.82,
        max: 6.14,
        usd: {
          min: "3.50",
          avg: "4.82",
          max: "6.14",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 33,
        item_name: "Coca-Cola, 0.33 liter Bottle",
        category_id: 6,
        category_name: "Restaurants",
        min: 1.5,
        avg: 2.17,
        max: 3,
        usd: {
          min: "1.50",
          avg: "2.17",
          max: "3.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 34,
        item_name: "Domestic Beer, 0.5 liter Draught",
        category_id: 6,
        category_name: "Restaurants",
        min: 5,
        avg: 7.35,
        max: 10,
        usd: {
          min: "5.00",
          avg: "7.35",
          max: "10.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 35,
        item_name: "Imported Beer, 0.33 liter Bottle",
        category_id: 6,
        category_name: "Restaurants",
        min: 7,
        avg: 8.73,
        max: 12,
        usd: {
          min: "7.00",
          avg: "8.73",
          max: "12.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 36,
        item_name: "McMeal at McDonalds or Alternative Combo Meal",
        category_id: 6,
        category_name: "Restaurants",
        min: 8,
        avg: 9.5,
        max: 11,
        usd: {
          min: "8.00",
          avg: "9.50",
          max: "11.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 37,
        item_name: "Meal for 2 People, Mid-range Restaurant, Three-course",
        category_id: 6,
        category_name: "Restaurants",
        min: 70,
        avg: 100,
        max: 150,
        usd: {
          min: "70.00",
          avg: "100.00",
          max: "150.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 38,
        item_name: "Meal in Inexpensive Restaurant",
        category_id: 6,
        category_name: "Restaurants",
        min: 12,
        avg: 20,
        max: 40,
        usd: {
          min: "12.00",
          avg: "20.00",
          max: "40.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 40,
        item_name: "Average Monthly Net Salary, After Tax",
        category_id: 7,
        category_name: "Salaries And Financing",
        min: 5420.69,
        avg: 6022.99,
        max: 6625.29,
        usd: {
          min: "5420.69",
          avg: "6022.99",
          max: "6625.29",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 42,
        item_name: "Cinema ticket, 1 Seat",
        category_id: 8,
        category_name: "Sports And Leisure",
        min: 15,
        avg: 16,
        max: 20,
        usd: {
          min: "15.00",
          avg: "16.00",
          max: "20.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 43,
        item_name: "Fitness Club, Monthly Fee for 1 Adult",
        category_id: 8,
        category_name: "Sports And Leisure",
        min: 25,
        avg: 86.16,
        max: 180,
        usd: {
          min: "25.00",
          avg: "86.16",
          max: "180.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 44,
        item_name: "Tennis Court Rent, 1 Hour on Weekend",
        category_id: 8,
        category_name: "Sports And Leisure",
        min: 20,
        avg: 36.75,
        max: 53.5,
        usd: {
          min: "20.00",
          avg: "36.75",
          max: "53.50",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 45,
        item_name: "Gasoline, 1 liter",
        category_id: 9,
        category_name: "Transportation",
        min: 0.58,
        avg: 0.71,
        max: 0.87,
        usd: {
          min: "0.58",
          avg: "0.71",
          max: "0.87",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 46,
        item_name: "Monthly Pass, Regular Price",
        category_id: 9,
        category_name: "Transportation",
        min: 114.3,
        avg: 127,
        max: 139.7,
        usd: {
          min: "114.30",
          avg: "127.00",
          max: "139.70",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 47,
        item_name: "One-way Ticket, Local Transport",
        category_id: 9,
        category_name: "Transportation",
        min: 2.48,
        avg: 2.75,
        max: 3.03,
        usd: {
          min: "2.48",
          avg: "2.75",
          max: "3.03",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 48,
        item_name: "Taxi, price for 1 hour Waiting, Normal Tariff",
        category_id: 9,
        category_name: "Transportation",
        min: 30,
        avg: 35,
        max: 60,
        usd: {
          min: "30.00",
          avg: "35.00",
          max: "60.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 49,
        item_name: "Taxi, price for 1 km, Normal Tariff",
        category_id: 9,
        category_name: "Transportation",
        min: 1.55,
        avg: 1.86,
        max: 3.11,
        usd: {
          min: "1.55",
          avg: "1.86",
          max: "3.11",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 50,
        item_name: "Taxi Start, Normal Tariff",
        category_id: 9,
        category_name: "Transportation",
        min: 2.5,
        avg: 3.5,
        max: 6,
        usd: {
          min: "2.50",
          avg: "3.50",
          max: "6.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 52,
        item_name:
          "Volkswagen Golf 1.4 90 KW Trendline (Or Equivalent New Car)",
        category_id: 9,
        category_name: "Transportation",
        min: 20000,
        avg: 22000,
        max: 30000,
        usd: {
          min: "20000.00",
          avg: "22000.00",
          max: "30000.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 53,
        item_name:
          "Prepaid Mobile Tariff Local, price per 1 min, No Discounts or Plans",
        category_id: 10,
        category_name: "Utilities Per Month",
        min: 0.05,
        avg: 0.11,
        max: 0.17,
        usd: {
          min: "0.05",
          avg: "0.11",
          max: "0.17",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 54,
        item_name:
          "Basic utilities for 85 square meter Apartment including Electricity, Heating or Cooling, Water and Garbage",
        category_id: 10,
        category_name: "Utilities Per Month",
        min: 80,
        avg: 148.86,
        max: 255,
        usd: {
          min: "80.00",
          avg: "148.86",
          max: "255.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 55,
        item_name: "Internet, 60 Mbps or More, Unlimited Data, Cable/ADSL",
        category_id: 10,
        category_name: "Utilities Per Month",
        min: 49,
        avg: 64.06,
        max: 90,
        usd: {
          min: "49.00",
          avg: "64.06",
          max: "90.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 58,
        item_name: "Water, 0.33 liter Bottle",
        category_id: 4,
        category_name: "Markets",
        min: 1.25,
        avg: 1.75,
        max: 3,
        usd: {
          min: "1.25",
          avg: "1.75",
          max: "3.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 64,
        item_name: "Summer Dress in a Chain Store Like George, H&M, Zara, etc.",
        category_id: 3,
        category_name: "Clothing And Shoes",
        min: 17,
        avg: 41.8,
        max: 70,
        usd: {
          min: "17.00",
          avg: "41.80",
          max: "70.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 65,
        item_name:
          "Mortgage Interest Rate in Percentages for 20 Years Fixed-Rate, Yearly, Fixed-Rate",
        category_id: 7,
        category_name: "Salaries And Financing",
        min: 3.39,
        avg: 3.77,
        max: 4.15,
        measure: "percent",
      },
      {
        good_id: 68,
        item_name: "Imported Beer, 0.33 liter Bottle",
        category_id: 4,
        category_name: "Markets",
        min: 2,
        avg: 3.01,
        max: 5,
        usd: {
          min: "2.00",
          avg: "3.01",
          max: "5.00",
        },
        measure: "money",
        currency_code: "USD",
      },
    ],
    error: null,
  },
  2334: {
    city_id: 2334,
    city_name: "Austin",
    state_code: "TX",
    country_name: "United States",
    exchange_rate: {
      EUR: 0.8530996522765817,
      AUD: 1.5460733529205013,
      USD: 1,
      CAD: 1.3874505628751503,
      CNY: 7.167751809424363,
      CZK: 20.92320311620241,
      DKK: 6.369037259980413,
      GBP: 0.7452951554176945,
      HKD: 7.8144576504270615,
      JPY: 147.6050438663841,
      NZD: 1.7046091268013197,
      NOK: 10.056600602629594,
      RUB: 79.83285389132875,
      KRW: 1384.2007249640844,
      CHF: 0.8081242386085603,
      UAH: 40.87732085760402,
      SEK: 9.493348382011199,
    },
    exchange_rates_updated: {
      date: "2025-08-24",
      timestamp: 1756058657,
    },
    prices: [
      {
        good_id: 1,
        item_name:
          "Price per square meter to Buy Apartment Outside of City Center",
        category_id: 1,
        category_name: "Buy Apartment",
        min: 1472.19,
        avg: 2026.72,
        max: 3229.17,
        usd: {
          min: "1472.19",
          avg: "2026.72",
          max: "3229.17",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 2,
        item_name: "Price per square meter to Buy Apartment in City Center",
        category_id: 1,
        category_name: "Buy Apartment",
        min: 1883.68,
        avg: 4366.88,
        max: 14238.49,
        usd: {
          min: "1883.68",
          avg: "4366.88",
          max: "14238.49",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 3,
        item_name: "International Primary School, Yearly for 1 Child",
        category_id: 2,
        category_name: "Childcare",
        min: 6000,
        avg: 17000,
        max: 32000,
        usd: {
          min: "6000.00",
          avg: "17000.00",
          max: "32000.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 4,
        item_name: "Private Preschool or Kindergarten, Monthly for 1 Child",
        category_id: 2,
        category_name: "Childcare",
        min: 683,
        avg: 991.06,
        max: 1600,
        usd: {
          min: "683.00",
          avg: "991.06",
          max: "1600.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 5,
        item_name:
          "Pair of Jeans in a Chain Store Like George, H&M, Zara, etc.",
        category_id: 3,
        category_name: "Clothing And Shoes",
        min: 19,
        avg: 38.6,
        max: 60,
        usd: {
          min: "19.00",
          avg: "38.60",
          max: "60.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 6,
        item_name: "Pair of Leather Business Shoes",
        category_id: 3,
        category_name: "Clothing And Shoes",
        min: 35,
        avg: 89.92,
        max: 144.84,
        usd: {
          min: "35.00",
          avg: "89.92",
          max: "144.84",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 7,
        item_name: "Pair of Running Shoes, Mid-Range Price",
        category_id: 3,
        category_name: "Clothing And Shoes",
        min: 50,
        avg: 76.09,
        max: 110,
        usd: {
          min: "50.00",
          avg: "76.09",
          max: "110.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 9,
        item_name: "Apples, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 1.1,
        avg: 3.4,
        max: 7.91,
        usd: {
          min: "1.10",
          avg: "3.40",
          max: "7.91",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 10,
        item_name: "Banana, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 0.84,
        avg: 1.27,
        max: 2.25,
        usd: {
          min: "0.84",
          avg: "1.27",
          max: "2.25",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 11,
        item_name: "Beef Round or Equivalent Back Leg Red Meat, 1 kg ",
        category_id: 4,
        category_name: "Markets",
        min: 3.31,
        avg: 11.79,
        max: 22.02,
        usd: {
          min: "3.31",
          avg: "11.79",
          max: "22.02",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 12,
        item_name: "Bottle of Wine, Mid-Range Price",
        category_id: 4,
        category_name: "Markets",
        min: 8,
        avg: 12,
        max: 17,
        usd: {
          min: "8.00",
          avg: "12.00",
          max: "17.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 13,
        item_name: "Chicken Breasts, Boneless and Skinless, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 2.2,
        avg: 7.66,
        max: 14.53,
        usd: {
          min: "2.20",
          avg: "7.66",
          max: "14.53",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 14,
        item_name: "Domestic Beer, 0.5 liter Bottle",
        category_id: 4,
        category_name: "Markets",
        min: 0.85,
        avg: 1.96,
        max: 3.57,
        usd: {
          min: "0.85",
          avg: "1.96",
          max: "3.57",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 15,
        item_name: "Eggs, 12 pack",
        category_id: 4,
        category_name: "Markets",
        min: 1.25,
        avg: 2.52,
        max: 3.79,
        usd: {
          min: "1.25",
          avg: "2.52",
          max: "3.79",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 17,
        item_name: "Lettuce, 1 head",
        category_id: 4,
        category_name: "Markets",
        min: 0.5,
        avg: 1.77,
        max: 3.04,
        usd: {
          min: "0.50",
          avg: "1.77",
          max: "3.04",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 18,
        item_name: "Loaf of Fresh White Bread, 0.5 kg",
        category_id: 4,
        category_name: "Markets",
        min: 1.1,
        avg: 2.19,
        max: 3.86,
        usd: {
          min: "1.10",
          avg: "2.19",
          max: "3.86",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 19,
        item_name: "Local Cheese, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 3.7,
        avg: 10.33,
        max: 22.05,
        usd: {
          min: "3.70",
          avg: "10.33",
          max: "22.05",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 20,
        item_name: "Milk, Regular,1 liter",
        category_id: 4,
        category_name: "Markets",
        min: 0.6,
        avg: 0.81,
        max: 1.06,
        usd: {
          min: "0.60",
          avg: "0.81",
          max: "1.06",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 21,
        item_name: "Onion, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 1.1,
        avg: 2.15,
        max: 4.34,
        usd: {
          min: "1.10",
          avg: "2.15",
          max: "4.34",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 22,
        item_name: "Oranges, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 1.1,
        avg: 3.47,
        max: 6.61,
        usd: {
          min: "1.10",
          avg: "3.47",
          max: "6.61",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 23,
        item_name: "Pack of Cigarettes",
        category_id: 4,
        category_name: "Markets",
        min: 6,
        avg: 7,
        max: 9.99,
        usd: {
          min: "6.00",
          avg: "7.00",
          max: "9.99",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 24,
        item_name: "Potato, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 0.77,
        avg: 2.31,
        max: 5.05,
        usd: {
          min: "0.77",
          avg: "2.31",
          max: "5.05",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 25,
        item_name: "White Rice, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 1.32,
        avg: 3.03,
        max: 4.96,
        usd: {
          min: "1.32",
          avg: "3.03",
          max: "4.96",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 26,
        item_name: "Tomato, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 1.1,
        avg: 3.52,
        max: 8.82,
        usd: {
          min: "1.10",
          avg: "3.52",
          max: "8.82",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 27,
        item_name: "Water, 1.5 liter Bottle",
        category_id: 4,
        category_name: "Markets",
        min: 0.4,
        avg: 1.53,
        max: 2.66,
        usd: {
          min: "0.40",
          avg: "1.53",
          max: "2.66",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 28,
        item_name: "One bedroom apartment outside of city centre",
        category_id: 5,
        category_name: "Rent Per Month",
        min: 950,
        avg: 1091.27,
        max: 1500,
        usd: {
          min: "950.00",
          avg: "1091.27",
          max: "1500.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 29,
        item_name: "One bedroom apartment in city centre",
        category_id: 5,
        category_name: "Rent Per Month",
        min: 1200,
        avg: 1703.34,
        max: 2500,
        usd: {
          min: "1200.00",
          avg: "1703.34",
          max: "2500.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 30,
        item_name: "Three bedroom apartment outside of city centre",
        category_id: 5,
        category_name: "Rent Per Month",
        min: 1500,
        avg: 1848.89,
        max: 2500,
        usd: {
          min: "1500.00",
          avg: "1848.89",
          max: "2500.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 31,
        item_name: "Three bedroom apartment in city centre",
        category_id: 5,
        category_name: "Rent Per Month",
        min: 2000,
        avg: 3119.23,
        max: 4500,
        usd: {
          min: "2000.00",
          avg: "3119.23",
          max: "4500.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 32,
        item_name: "Cappuccino",
        category_id: 6,
        category_name: "Restaurants",
        min: 1.08,
        avg: 3.95,
        max: 6.82,
        usd: {
          min: "1.08",
          avg: "3.95",
          max: "6.82",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 33,
        item_name: "Coca-Cola, 0.33 liter Bottle",
        category_id: 6,
        category_name: "Restaurants",
        min: 1,
        avg: 1.97,
        max: 3,
        usd: {
          min: "1.00",
          avg: "1.97",
          max: "3.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 34,
        item_name: "Domestic Beer, 0.5 liter Draught",
        category_id: 6,
        category_name: "Restaurants",
        min: 2,
        avg: 4,
        max: 6,
        usd: {
          min: "2.00",
          avg: "4.00",
          max: "6.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 35,
        item_name: "Imported Beer, 0.33 liter Bottle",
        category_id: 6,
        category_name: "Restaurants",
        min: 4,
        avg: 6,
        max: 8,
        usd: {
          min: "4.00",
          avg: "6.00",
          max: "8.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 36,
        item_name: "McMeal at McDonalds or Alternative Combo Meal",
        category_id: 6,
        category_name: "Restaurants",
        min: 6,
        avg: 7.5,
        max: 9,
        usd: {
          min: "6.00",
          avg: "7.50",
          max: "9.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 37,
        item_name: "Meal for 2 People, Mid-range Restaurant, Three-course",
        category_id: 6,
        category_name: "Restaurants",
        min: 35,
        avg: 50,
        max: 80,
        usd: {
          min: "35.00",
          avg: "50.00",
          max: "80.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 38,
        item_name: "Meal in Inexpensive Restaurant",
        category_id: 6,
        category_name: "Restaurants",
        min: 5.63,
        avg: 15,
        max: 24.37,
        usd: {
          min: "5.63",
          avg: "15.00",
          max: "24.37",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 40,
        item_name: "Average Monthly Net Salary, After Tax",
        category_id: 7,
        category_name: "Salaries And Financing",
        min: 4030.13,
        avg: 4477.92,
        max: 4925.71,
        usd: {
          min: "4030.13",
          avg: "4477.92",
          max: "4925.71",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 42,
        item_name: "Cinema ticket, 1 Seat",
        category_id: 8,
        category_name: "Sports And Leisure",
        min: 8.5,
        avg: 12,
        max: 15.5,
        usd: {
          min: "8.50",
          avg: "12.00",
          max: "15.50",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 43,
        item_name: "Fitness Club, Monthly Fee for 1 Adult",
        category_id: 8,
        category_name: "Sports And Leisure",
        min: 11,
        avg: 37.93,
        max: 64.86,
        usd: {
          min: "11.00",
          avg: "37.93",
          max: "64.86",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 44,
        item_name: "Tennis Court Rent, 1 Hour on Weekend",
        category_id: 8,
        category_name: "Sports And Leisure",
        min: 7.07,
        avg: 7.86,
        max: 8.65,
        usd: {
          min: "7.07",
          avg: "7.86",
          max: "8.65",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 45,
        item_name: "Gasoline, 1 liter",
        category_id: 9,
        category_name: "Transportation",
        min: 0.43,
        avg: 0.53,
        max: 0.65,
        usd: {
          min: "0.43",
          avg: "0.53",
          max: "0.65",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 46,
        item_name: "Monthly Pass, Regular Price",
        category_id: 9,
        category_name: "Transportation",
        min: 32,
        avg: 41.25,
        max: 96.25,
        usd: {
          min: "32.00",
          avg: "41.25",
          max: "96.25",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 47,
        item_name: "One-way Ticket, Local Transport",
        category_id: 9,
        category_name: "Transportation",
        min: 1.12,
        avg: 1.25,
        max: 1.38,
        usd: {
          min: "1.12",
          avg: "1.25",
          max: "1.38",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 48,
        item_name: "Taxi, price for 1 hour Waiting, Normal Tariff",
        category_id: 9,
        category_name: "Transportation",
        min: 20,
        avg: 29,
        max: 38,
        usd: {
          min: "20.00",
          avg: "29.00",
          max: "38.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 49,
        item_name: "Taxi, price for 1 km, Normal Tariff",
        category_id: 9,
        category_name: "Transportation",
        min: 1.37,
        avg: 1.55,
        max: 3.11,
        usd: {
          min: "1.37",
          avg: "1.55",
          max: "3.11",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 50,
        item_name: "Taxi Start, Normal Tariff",
        category_id: 9,
        category_name: "Transportation",
        min: 1.5,
        avg: 2.5,
        max: 5,
        usd: {
          min: "1.50",
          avg: "2.50",
          max: "5.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 52,
        item_name:
          "Volkswagen Golf 1.4 90 KW Trendline (Or Equivalent New Car)",
        category_id: 9,
        category_name: "Transportation",
        min: 18000,
        avg: 21422.5,
        max: 25000,
        usd: {
          min: "18000.00",
          avg: "21422.50",
          max: "25000.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 53,
        item_name:
          "Prepaid Mobile Tariff Local, price per 1 min, No Discounts or Plans",
        category_id: 10,
        category_name: "Utilities Per Month",
        min: 0.01,
        avg: 0.09,
        max: 0.2,
        usd: {
          min: "0.01",
          avg: "0.09",
          max: "0.20",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 54,
        item_name:
          "Basic utilities for 85 square meter Apartment including Electricity, Heating or Cooling, Water and Garbage",
        category_id: 10,
        category_name: "Utilities Per Month",
        min: 85,
        avg: 140.86,
        max: 212.5,
        usd: {
          min: "85.00",
          avg: "140.86",
          max: "212.50",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 55,
        item_name: "Internet, 60 Mbps or More, Unlimited Data, Cable/ADSL",
        category_id: 10,
        category_name: "Utilities Per Month",
        min: 50,
        avg: 62.61,
        max: 100,
        usd: {
          min: "50.00",
          avg: "62.61",
          max: "100.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 58,
        item_name: "Water, 0.33 liter Bottle",
        category_id: 4,
        category_name: "Markets",
        min: 1,
        avg: 1.46,
        max: 2.75,
        usd: {
          min: "1.00",
          avg: "1.46",
          max: "2.75",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 64,
        item_name: "Summer Dress in a Chain Store Like George, H&M, Zara, etc.",
        category_id: 3,
        category_name: "Clothing And Shoes",
        min: 15,
        avg: 35.48,
        max: 55.96,
        usd: {
          min: "15.00",
          avg: "35.48",
          max: "55.96",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 65,
        item_name:
          "Mortgage Interest Rate in Percentages for 20 Years Fixed-Rate, Yearly, Fixed-Rate",
        category_id: 7,
        category_name: "Salaries And Financing",
        min: 3.4,
        avg: 3.78,
        max: 4.16,
        measure: "percent",
      },
      {
        good_id: 68,
        item_name: "Imported Beer, 0.33 liter Bottle",
        category_id: 4,
        category_name: "Markets",
        min: 0.95,
        avg: 2.05,
        max: 4,
        usd: {
          min: "0.95",
          avg: "2.05",
          max: "4.00",
        },
        measure: "money",
        currency_code: "USD",
      },
    ],
    error: null,
  },
};
