expenseGoodIds = {
  housing: [28,29,30,31],
  utilities: [54,55],
  transportation: [45,46,47],
  food: [9,10,11,13,15,17,18,19,20,21,22,24,25,26,27,58],
  other: [3,4]
}

lifestyleGoodIds = {
  diningOut: [32,33,34,35,36,37,38],
  entertainment: [42,43,44]
}

export const fallbackCityPrices = {
  2746: {
    city_id: 2746,
    city_name: "Pensacola",
    state_code: "FL",
    country_name: "United States",
    exchange_rate: {
      EUR: 0.8530996522765817,
      AUD: 1.5460733529205013,
      USD: 1,
      CAD: 1.3874505628751503,
      CNY: 7.167751809424363,
      CZK: 20.92320311620241,
      DKK: 6.369037259980413,
      GBP: 0.7452951554176945,
      HKD: 7.8144576504270615,
      JPY: 147.6050438663841,
      NZD: 1.7046091268013197,
      NOK: 10.056600602629594,
      RUB: 79.83285389132875,
      KRW: 1384.2007249640844,
      CHF: 0.8081242386085603,
      UAH: 40.87732085760402,
      SEK: 9.493348382011199,
    },
    exchange_rates_updated: {
      date: "2025-08-24",
      timestamp: 1756058657,
    },
    prices: [
      {
        good_id: 1,
        item_name:
          "Price per square meter to Buy Apartment Outside of City Center",
        category_id: 1,
        category_name: "Buy Apartment",
        min: 906.56,
        avg: 979.96,
        max: 1065.63,
        usd: {
          min: "906.56",
          avg: "979.96",
          max: "1065.63",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 2,
        item_name: "Price per square meter to Buy Apartment in City Center",
        category_id: 1,
        category_name: "Buy Apartment",
        min: 1510.53,
        avg: 2166.62,
        max: 2822.71,
        usd: {
          min: "1510.53",
          avg: "2166.62",
          max: "2822.71",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 3,
        item_name: "International Primary School, Yearly for 1 Child",
        category_id: 2,
        category_name: "Childcare",
        min: 9000,
        avg: 10000,
        max: 11000,
        usd: {
          min: "9000.00",
          avg: "10000.00",
          max: "11000.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 4,
        item_name: "Private Preschool or Kindergarten, Monthly for 1 Child",
        category_id: 2,
        category_name: "Childcare",
        min: 360,
        avg: 733.33,
        max: 1200,
        usd: {
          min: "360.00",
          avg: "733.33",
          max: "1200.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 5,
        item_name:
          "Pair of Jeans in a Chain Store Like George, H&M, Zara, etc.",
        category_id: 3,
        category_name: "Clothing And Shoes",
        min: 29.99,
        avg: 48.75,
        max: 69,
        usd: {
          min: "29.99",
          avg: "48.75",
          max: "69.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 6,
        item_name: "Pair of Leather Business Shoes",
        category_id: 3,
        category_name: "Clothing And Shoes",
        min: 50,
        avg: 100,
        max: 150,
        usd: {
          min: "50.00",
          avg: "100.00",
          max: "150.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 7,
        item_name: "Pair of Running Shoes, Mid-Range Price",
        category_id: 3,
        category_name: "Clothing And Shoes",
        min: 53,
        avg: 83.57,
        max: 114.14,
        usd: {
          min: "53.00",
          avg: "83.57",
          max: "114.14",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 9,
        item_name: "Apples, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 2.2,
        avg: 5.32,
        max: 11.02,
        usd: {
          min: "2.20",
          avg: "5.32",
          max: "11.02",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 10,
        item_name: "Banana, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 1.1,
        avg: 2.12,
        max: 3.97,
        usd: {
          min: "1.10",
          avg: "2.12",
          max: "3.97",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 11,
        item_name: "Beef Round or Equivalent Back Leg Red Meat, 1 kg ",
        category_id: 4,
        category_name: "Markets",
        min: 11,
        avg: 17.51,
        max: 24.02,
        usd: {
          min: "11.00",
          avg: "17.51",
          max: "24.02",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 12,
        item_name: "Bottle of Wine, Mid-Range Price",
        category_id: 4,
        category_name: "Markets",
        min: 5,
        avg: 7,
        max: 10,
        usd: {
          min: "5.00",
          avg: "7.00",
          max: "10.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 13,
        item_name: "Chicken Breasts, Boneless and Skinless, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 4.12,
        avg: 7.22,
        max: 15.41,
        usd: {
          min: "4.12",
          avg: "7.22",
          max: "15.41",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 14,
        item_name: "Domestic Beer, 0.5 liter Bottle",
        category_id: 4,
        category_name: "Markets",
        min: 0.94,
        avg: 1.81,
        max: 3,
        usd: {
          min: "0.94",
          avg: "1.81",
          max: "3.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 15,
        item_name: "Eggs, 12 pack",
        category_id: 4,
        category_name: "Markets",
        min: 1.2,
        avg: 2.24,
        max: 3.28,
        usd: {
          min: "1.20",
          avg: "2.24",
          max: "3.28",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 17,
        item_name: "Lettuce, 1 head",
        category_id: 4,
        category_name: "Markets",
        min: 1.28,
        avg: 1.59,
        max: 2,
        usd: {
          min: "1.28",
          avg: "1.59",
          max: "2.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 18,
        item_name: "Loaf of Fresh White Bread, 0.5 kg",
        category_id: 4,
        category_name: "Markets",
        min: 1.65,
        avg: 2.97,
        max: 4.29,
        usd: {
          min: "1.65",
          avg: "2.97",
          max: "4.29",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 19,
        item_name: "Local Cheese, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 6.61,
        avg: 7.1,
        max: 8.07,
        usd: {
          min: "6.61",
          avg: "7.10",
          max: "8.07",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 20,
        item_name: "Milk, Regular,1 liter",
        category_id: 4,
        category_name: "Markets",
        min: 0.88,
        avg: 1.1,
        max: 1.32,
        usd: {
          min: "0.88",
          avg: "1.10",
          max: "1.32",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 21,
        item_name: "Onion, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 1.94,
        avg: 2.62,
        max: 3.73,
        usd: {
          min: "1.94",
          avg: "2.62",
          max: "3.73",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 22,
        item_name: "Oranges, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 2.2,
        avg: 2.23,
        max: 2.27,
        usd: {
          min: "2.20",
          avg: "2.23",
          max: "2.27",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 23,
        item_name: "Pack of Cigarettes",
        category_id: 4,
        category_name: "Markets",
        min: 6.5,
        avg: 7,
        max: 13,
        usd: {
          min: "6.50",
          avg: "7.00",
          max: "13.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 24,
        item_name: "Potato, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 1.3,
        avg: 2.53,
        max: 3.76,
        usd: {
          min: "1.30",
          avg: "2.53",
          max: "3.76",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 25,
        item_name: "White Rice, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 1.59,
        avg: 2.94,
        max: 4.41,
        usd: {
          min: "1.59",
          avg: "2.94",
          max: "4.41",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 26,
        item_name: "Tomato, 1 kg",
        category_id: 4,
        category_name: "Markets",
        min: 1.1,
        avg: 3.77,
        max: 6.44,
        usd: {
          min: "1.10",
          avg: "3.77",
          max: "6.44",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 27,
        item_name: "Water, 1.5 liter Bottle",
        category_id: 4,
        category_name: "Markets",
        min: 1.2,
        avg: 1.76,
        max: 2.32,
        usd: {
          min: "1.20",
          avg: "1.76",
          max: "2.32",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 28,
        item_name: "One bedroom apartment outside of city centre",
        category_id: 5,
        category_name: "Rent Per Month",
        min: 650,
        avg: 838,
        max: 1200,
        usd: {
          min: "650.00",
          avg: "838.00",
          max: "1200.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 29,
        item_name: "One bedroom apartment in city centre",
        category_id: 5,
        category_name: "Rent Per Month",
        min: 850,
        avg: 988.89,
        max: 1200,
        usd: {
          min: "850.00",
          avg: "988.89",
          max: "1200.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 30,
        item_name: "Three bedroom apartment outside of city centre",
        category_id: 5,
        category_name: "Rent Per Month",
        min: 1000,
        avg: 1293.89,
        max: 1800,
        usd: {
          min: "1000.00",
          avg: "1293.89",
          max: "1800.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 31,
        item_name: "Three bedroom apartment in city centre",
        category_id: 5,
        category_name: "Rent Per Month",
        min: 1200,
        avg: 1566.11,
        max: 2500,
        usd: {
          min: "1200.00",
          avg: "1566.11",
          max: "2500.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 32,
        item_name: "Cappuccino",
        category_id: 6,
        category_name: "Restaurants",
        min: 3,
        avg: 3.83,
        max: 5,
        usd: {
          min: "3.00",
          avg: "3.83",
          max: "5.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 33,
        item_name: "Coca-Cola, 0.33 liter Bottle",
        category_id: 6,
        category_name: "Restaurants",
        min: 1.75,
        avg: 1.88,
        max: 2.01,
        usd: {
          min: "1.75",
          avg: "1.88",
          max: "2.01",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 34,
        item_name: "Domestic Beer, 0.5 liter Draught",
        category_id: 6,
        category_name: "Restaurants",
        min: 3.6,
        avg: 4,
        max: 4.4,
        usd: {
          min: "3.60",
          avg: "4.00",
          max: "4.40",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 35,
        item_name: "Imported Beer, 0.33 liter Bottle",
        category_id: 6,
        category_name: "Restaurants",
        min: 4.5,
        avg: 5,
        max: 5.5,
        usd: {
          min: "4.50",
          avg: "5.00",
          max: "5.50",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 36,
        item_name: "McMeal at McDonalds or Alternative Combo Meal",
        category_id: 6,
        category_name: "Restaurants",
        min: 6,
        avg: 7,
        max: 8,
        usd: {
          min: "6.00",
          avg: "7.00",
          max: "8.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 37,
        item_name: "Meal for 2 People, Mid-range Restaurant, Three-course",
        category_id: 6,
        category_name: "Restaurants",
        min: 45,
        avg: 50,
        max: 55,
        usd: {
          min: "45.00",
          avg: "50.00",
          max: "55.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 38,
        item_name: "Meal in Inexpensive Restaurant",
        category_id: 6,
        category_name: "Restaurants",
        min: 9,
        avg: 10,
        max: 11,
        usd: {
          min: "9.00",
          avg: "10.00",
          max: "11.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 40,
        item_name: "Average Monthly Net Salary, After Tax",
        category_id: 7,
        category_name: "Salaries And Financing",
        min: 1856.7,
        avg: 2063,
        max: 2269.3,
        usd: {
          min: "1856.70",
          avg: "2063.00",
          max: "2269.30",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 42,
        item_name: "Cinema ticket, 1 Seat",
        category_id: 8,
        category_name: "Sports And Leisure",
        min: 8,
        avg: 10,
        max: 12,
        usd: {
          min: "8.00",
          avg: "10.00",
          max: "12.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 43,
        item_name: "Fitness Club, Monthly Fee for 1 Adult",
        category_id: 8,
        category_name: "Sports And Leisure",
        min: 19,
        avg: 28.57,
        max: 45,
        usd: {
          min: "19.00",
          avg: "28.57",
          max: "45.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 44,
        item_name: "Tennis Court Rent, 1 Hour on Weekend",
        category_id: 8,
        category_name: "Sports And Leisure",
        min: 11.25,
        avg: 12.5,
        max: 13.75,
        usd: {
          min: "11.25",
          avg: "12.50",
          max: "13.75",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 45,
        item_name: "Gasoline, 1 liter",
        category_id: 9,
        category_name: "Transportation",
        min: 0.5,
        avg: 0.6,
        max: 0.7,
        usd: {
          min: "0.50",
          avg: "0.60",
          max: "0.70",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 46,
        item_name: "Monthly Pass, Regular Price",
        category_id: 9,
        category_name: "Transportation",
        min: 35,
        avg: 45,
        max: 100,
        usd: {
          min: "35.00",
          avg: "45.00",
          max: "100.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 47,
        item_name: "One-way Ticket, Local Transport",
        category_id: 9,
        category_name: "Transportation",
        min: 1,
        avg: 1.5,
        max: 2,
        usd: {
          min: "1.00",
          avg: "1.50",
          max: "2.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 48,
        item_name: "Taxi, price for 1 hour Waiting, Normal Tariff",
        category_id: 9,
        category_name: "Transportation",
        min: 20,
        avg: 26,
        max: 32,
        usd: {
          min: "20.00",
          avg: "26.00",
          max: "32.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 49,
        item_name: "Taxi, price for 1 km, Normal Tariff",
        category_id: 9,
        category_name: "Transportation",
        min: 1.24,
        avg: 1.4,
        max: 2.49,
        usd: {
          min: "1.24",
          avg: "1.40",
          max: "2.49",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 50,
        item_name: "Taxi Start, Normal Tariff",
        category_id: 9,
        category_name: "Transportation",
        min: 1.8,
        avg: 2,
        max: 2.2,
        usd: {
          min: "1.80",
          avg: "2.00",
          max: "2.20",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 52,
        item_name:
          "Volkswagen Golf 1.4 90 KW Trendline (Or Equivalent New Car)",
        category_id: 9,
        category_name: "Transportation",
        min: 19800,
        avg: 22000,
        max: 24200,
        usd: {
          min: "19800.00",
          avg: "22000.00",
          max: "24200.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 53,
        item_name:
          "Prepaid Mobile Tariff Local, price per 1 min, No Discounts or Plans",
        category_id: 10,
        category_name: "Utilities Per Month",
        min: 0.02,
        avg: 0.02,
        max: 0.02,
        usd: {
          min: "0.02",
          avg: "0.02",
          max: "0.02",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 54,
        item_name:
          "Basic utilities for 85 square meter Apartment including Electricity, Heating or Cooling, Water and Garbage",
        category_id: 10,
        category_name: "Utilities Per Month",
        min: 135,
        avg: 264.22,
        max: 564,
        usd: {
          min: "135.00",
          avg: "264.22",
          max: "564.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 55,
        item_name: "Internet, 60 Mbps or More, Unlimited Data, Cable/ADSL",
        category_id: 10,
        category_name: "Utilities Per Month",
        min: 50,
        avg: 64.78,
        max: 150,
        usd: {
          min: "50.00",
          avg: "64.78",
          max: "150.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 58,
        item_name: "Water, 0.33 liter Bottle",
        category_id: 4,
        category_name: "Markets",
        min: 1,
        avg: 1.39,
        max: 1.78,
        usd: {
          min: "1.00",
          avg: "1.39",
          max: "1.78",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 64,
        item_name: "Summer Dress in a Chain Store Like George, H&M, Zara, etc.",
        category_id: 3,
        category_name: "Clothing And Shoes",
        min: 20,
        avg: 34.83,
        max: 50,
        usd: {
          min: "20.00",
          avg: "34.83",
          max: "50.00",
        },
        measure: "money",
        currency_code: "USD",
      },
      {
        good_id: 65,
        item_name:
          "Mortgage Interest Rate in Percentages for 20 Years Fixed-Rate, Yearly, Fixed-Rate",
        category_id: 7,
        category_name: "Salaries And Financing",
        min: 3.67,
        avg: 4.08,
        max: 4.49,
        measure: "percent",
      },
      {
        good_id: 68,
        item_name: "Imported Beer, 0.33 liter Bottle",
        category_id: 4,
        category_name: "Markets",
        min: 1,
        avg: 3.17,
        max: 5.34,
        usd: {
          min: "1.00",
          avg: "3.17",
          max: "5.34",
        },
        measure: "money",
        currency_code: "USD",
      },
    ],
    error: null,
  },
};
